spring:
  database:
    driverClassName: org.hsqldb.jdbcDriver

  datasource:
    username: SA
    password: ''
    url: jdbc:hsqldb:mem:db

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

    show-sql: true